# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
darklua = "seaofvoices/darklua@0.16.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.53.1"
selene = "Kampfkarren/selene@0.29.0"
stylua = "JohnnyMorganz/stylua@2.1.0"
blink = "1Axen/blink@0.18.0"
asphalt = "jackTabsCode/asphalt@1.0.0-pre.14"
