name: CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  lint:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pesde
        uses: ssqvid/setup-pesde@main
        with:
          cache: true
          version: 0.7.0-rc.7
     
      - run: pesde install

      - name: Lint
        run: |
          chmod +x ./scripts/luau_lint.sh
          ./scripts/luau_lint.sh

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pesde
        uses: ssqvid/setup-pesde@main
        with:
          cache: true
          version: 0.7.0-rc.7

      - run: pesde install

      - name: Build Place
        run: |
          chmod +x ./scripts/luau_dist.sh
          ./scripts/luau_dist.sh

      - name: Run Unit Tests
        run: >
          lune
          run 
          upload 
          dist.rbxl 
          $TASK_FILE
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ vars.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.ROBLOX_TEST_PLACE_ID }}
          TASK_FILE: "tasks/runTests.luau"
